---
title: "Article analysis n°2: Food insecurity in young adults raises risk for diabetes, high blood pressure, asthma"
description: |
author:
  - name: Caroline Ransquin
date: 11-03-2019
output:
  distill::distill_article:
    self_contained: false
draft: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Magazine and Source :

Science Daily

<https://www.sciencedaily.com/releases/2019/10/191001165446.htm>

## Article : 

A paradox of food insecurity in wealthy countries is its association with excess weight. Now, a study led by researchers at UC San Francisco finds that young adults in the United States who are food insecure not only are slightly more likely to be obese, they are significantly more likely to suffer from disorders associated with high body mass index, as well as obstructive airway diseases like asthma.

In the study, which tracked close to 15,000 young adults who were representative of their peers nationwide, the researchers found that 1,647 (11 percent) were food insecure, defined as lacking "sufficient, safe and nutritious food that meets individuals' dietary needs and preferences for an active and healthy life."

The study appears in the Journal of General Internal Medicine on Oct. 1, 2019.

The researchers, led by first author Jason Nagata, MD, of the UCSF Department of Pediatrics, found a 7 percent difference between the two groups in the incidence of obesity: 36 percent of the food-secure group versus 43 percent for the food-insecure cohort.

### Cyclic Nature of Food Insecurity May Promote Diabetes

But when the researchers looked at the rate of diabetes among the 14,786 participants, who were aged between 24 and 32, they found that more than twice as many in the food-insecure group -- 5.1 percent compared with 2.2 percent -- said that they had been told by a medical provider that they had diabetes.

"The cyclic nature of food insecurity, reflective of monthly paychecks and food assistance, may promote insulin resistance, due to alternating periods of food abundance and food shortage," said Nagata. Other factors that may play a role in diabetes include the consumption of cheaper, calorie-dense foods with a high content of fats and carbohydrates, and a low intake of fresh fruits and vegetables, he said.

The food-insecure group was also more likely to report that they had been told by a medical provider that they had high blood pressure: 16 percent versus 11 percent for the food-secure participants.

"Chronic stress from food insecurity may contribute to insulin resistance, obesity and high blood pressure," said senior author Sheri Weiser, MD, of the UCSF Department of Medicine. "Stress can activate the neuro-endocrine system and stimulate the release of glucocorticoids, which can alter metabolism, lead to increased fat accumulation and storage, and amplify binge-eating behavior."

### Stress Linked to Inflammation, a Factor in Asthma

Stress also plays a role in asthma, as well as other obstructive airway diseases like chronic bronchitis or emphysema. Among the food-secure group, 14 percent said they had been told by a medical provider that they had at least one of these conditions, compared with 21 percent of the food-insecure participants.

The higher rate of smoking in the food-insecure group (46 percent versus 28 percent) may partially explain the disparity between the two groups, but stress is believed to lead to greater inflammation, which is implicated in asthma and asthma exacerbations, the authors noted. Additionally, food insecurity may lead to increased susceptibility to infections, which may boost the risk for asthma and bronchitis, they said.

A second study, also led by Nagata, found that the same cohort of food-insecure young adults was at higher risk for mental health issues compared to their food-secure peers. Some 15 percent of the food-secure group had a depression diagnosis, compared with 29 percent for the food-insecure participants. A suicide attempt within the past 12 months was reported by 1.3 percent of the food-secure group, versus 3.6 percent for the food-insecure participants. Diagnoses for anxiety or panic disorder, and difficulties falling and staying asleep were also significantly higher among the food-insecure young adults.

## Vocabulary : 

| Word from the text | Synonym/explanation in English |
|--------------------|--------------------------------|
|Wealthy             |Prosperous                      |
|Weight              |A system of units for expressing heaviness or mass|
|Led (to lead)       |Manage                          |
|Food insecure       |"sufficient, safe and nutritious food that meets individuals' dietary needs and preferences for an active and healthy life."|
|Slightly            |A little                        | 
|Likely              |Possessing or displaying the qualities or characteristics that make something probable|
|To suffer           |To feel pain or distress; sustain injury or harm|
|Discorders          |A condition of pain, disease, or malfunction|
|Body mass index     |IMC : A measurement of the relative percentages of fat and muscle mass in the human body|
|Obstructive airway diseases|A chronic, progressive lung disease in which there is poor airflow in the lungs, characterized by wheezing, shortness of breath with difficulty exhaling, and cough|
|To track            |To observe the progress         |
|Peers nationwide    |Persons with equal country or nation|
|Lacking             |Deficiency or absence          |
|Sufficient          |Being as much as is needed, adequate, enough|
|Safe                |Not exposed to the threat of danger or harm|
|Nutritious          |Providing nourishment           |
|Meets               |Provide for needs               | 
|Dietary needs       |Needs relating to diet          |
|Healthy             |Enjoying good health            |
|To appear           |To be published or made available to the public|
|To promote          |To contribute to the progress or growth of|
|Diabetes            |Any of a group of diseases characterized by high blood sugar levels caused by insufficient production of insulin| 
|Medical provider    |Healthcare professional         |
|Reflective          |Relating to                     |
|Monthly paychecks   |A check issued to an employee in payment of salary or wages each month|
|Insulin             |A polypeptide hormone that is secreted by the beta cells of the islets of Langerhans in the pancreas and functions in the regulation of carbohydrate and fat metabolism, especially the conversion of glucose to glycogen, which lowers the blood glucose level|
|Due                 |Because of                      |
|Shortage            |A deficiency in amount          | 
|Cheaper             |Shoddy                          |
|Fats                | A mixture of such compounds occurring widely in organic tissue, especially in the adipose tissue of animals and in the seeds, nuts, and fruits of plants|
|Intake              |A thing or a quantity taken in| 
|High blood pressure |A condition in which the pressure of the blood, especially in the arteries, is abnormally high|
|Neuro-endocrine system|Of, relating to, or involving the interaction between the nervous system and the hormones of the endocrine glands|
|Release             |To cause or allow to move away or spread from a source or place of confinement|
|Glucocorticoids     |Hormones that control the metabolism of fats and carbohydrates. They are produced in the cortex of each adrenal gland|
|Metabolism          |The chemical processes occurring within a living cell or organism that are necessary for the maintenance of life|
|Storage             |The act of storing goods        | 
|Binge-eating        |Consumption of large amounts of food in a short period of time, especially as a symptom of bulimia|
|Behavior            |The actions or reactions of a person|
|Linked              |Connected, especially by or as if by links|
|As well as          |Also, too|
|Chronic bronchitis  |Bronchitis is an inflammation of the air passages between the nose and the lungs, including the windpipe or trachea and the larger air tubes of the lung that bring air in from the trachea (bronchi) and lasting for a long period of time or marked by frequent recurrence|
|Emphysema           |A pathological condition of the lungs marked by an abnormal increase in the size of the air spaces, resulting in labored breathing and an increased susceptibility to infection|
|Greater             |greater in size or importance|
|Exacerbations       |Increase in severity of a disease or any of its symptoms|
|Additionally        |Also, besides|
|Boost               |To increase, raise|
|Mental health issues|Problems relating to the mind|
|Depression          |Sadness, dejection, esp. sadness greater and longer than considered normal|
|Panic discorder     |An anxiety disorder characterized by recurrent panic attacks and fear of further attacks|
|Falling asleep      |To go to sleep|

## Analysis table :

|                                   |                                                                                                                          |
| ----------------------------------| ------------------------------------------------------------------------------------------------------------------------|
|**Researchers**                |Jason Nagata of the Univercity San Francisco Department of Pediatrics and Sheri Weiser of the UCSF Department of Medicine.|
|**Published in, the magazine** |1 October 2019, Science Daily   |
|**General topic**              |Risk for diabetes, high blood pressure and asthma increaseswith food insecurity in young adults.|
|**Procedure/what was examined**|1)Study of 15000 young adults. 2)Look at the rate of diabetes, high blood pressure and obstructive airway diseases among the 14786 participants (24-32 years). 3)Risk for mental health issues in both groups.|
|**Conclusions/discovery**      |1)1647 (11%) of young adults were food insecure. Incidence of obesity : 36% of the food-secure group vs 43% for the food-insecure group. 2) 5,1% of the food-insecure group they have been told by a medical provider that they had diabetes (vs 2,2% for the food-secure group), 16% (vs 11%) for high blood pressure and 21% (vs 14%) for abstructive airway diseases. 3) 15% of the food-secure group had a depression diagnosis vs 29% for the food-insecure group. 1,3% of suicide attempt of the food-secure group vs 3,6% for the food-insecure group.| 
|**Remaining questions**        ||

## Sources of Synonyms and Explanations in English :

http://www.thefreedictionary.com/

https://www.wordreference.com/fr/

